#:kivy 2.3.1
#:import MDSharedAxisTransition kivymd.uix.transition.MDSharedAxisTransition

MDScreen:
	id: app_screen
	md_bg_color: app.theme_cls.backgroundColor

	BoxLayout:
		id: app_box_layout

		orientation: "vertical"
		# Later should be overriden in python based on the system running the app
#		size_hint_x: None
#		width: "500dp"
		md_bg_color: app.theme_cls.secondaryContainerColor
		size_hint_max_x: dp(500)
		pos_hint: {"center_x": 0.5}
        adaptive_height: True
        spacing: "12dp"
        pos_hint: {"center_x": .5}

		TopBar:
			id: top_bar

		MDScreenManager:
			id: screen_manager
			transition: MDSharedAxisTransition(transition_axis="x")

			SelectionScreen:
				name: "selection"

				on_pre_enter:
					app.refresh_selection_screen()

				on_leave:
					app.clear_selection_screen()

			VaultScreen:
				name: "vault"

				on_pre_enter:
					app.refresh_vault_screen()

				on_enter:
					app._resume_loading_account_batch()

				on_leave:
					app.clear_vault_screen()