#:kivy 2.3.1

MDScreen:
	id: app_screen
	md_bg_color: app.theme_cls.backgroundColor

	BoxLayout:
		id: app_box_layout

		orientation: "vertical"
		# Later should be overriden in python based on the system running the app
#		size_hint_x: None
#		width: "500dp"
		md_bg_color: app.theme_cls.secondaryContainerColor
		size_hint_max_x: dp(500)
		pos_hint: {"center_x": 0.5}
        adaptive_height: True
        spacing: "12dp"
        pos_hint: {"center_x": .5}

		TopBar:
			id: top_bar

		ScreenManager:
			id: screen_manager

			SelectionScreen:
				name: "selection"

				MDLabel:
					text: "Imported/Created vaults will appear here."
					adaptive_height: True
					pos_hint: {"center_x": 0.5, "center_y": 0.5}
					halign: "center"

