#:kivy 2.3.1

<TopBar>:
	type: "small"

	MDTopAppBarLeadingButtonContainer:

		MDActionTopAppBarButton:
			id: back_button
			icon: "arrow-left"
			on_release: root.on_back()

	MDTopAppBarTitle:
		text: "Simple Password Manager"

	MDTopAppBarTrailingButtonContainer:

		MDActionTopAppBarButton:
			id: import_vault_button
			icon: "file-import"

		MDActionTopAppBarButton:
			id: new_vault_button
			icon: "plus"

		MDActionTopAppBarButton:
			id: app_settings_button
			icon: "cog"